name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: update apt
      run: sudo apt update
    - name: install monero dependencies
      run: sudo apt install -y build-essential libtool cmake autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache docker
    - name: build
      run: cd .. && cp monero/contrib/gitian/gitian-build.py . && ./gitian-build.py --setup --docker monero master && ./gitian-build.py --build --docker --detach-sign --no-commit monero master
